name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Compliling the Code
      run: echo "Compilation process started"

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: test_ml_demo
        IMAGE_TAG: test_ml_image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Unit testing the Code
      run: echo "Unit testing Completed"
   
    - name: Code Analysis
      run: echo "Code Analysis (Lint, code scan SAST, SCA scan)"

#    - name: Publish Artifact
#      run: echo "Publish Artifact"

#    - name: Integration test
#      run: echo "Integration test"

#    - name: Deploy artifacts
#      run: echo "Deploy artifacts (Dev, Staging and then Prod)"
