name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compliling the Code
      run: echo "Compilation process started"

    - name: Unit testing the Code
      run: echo "Unit testing Completed"
   